[package]
name = "basalt_render"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.7"
wgpu = "0.17.1"
cfg-if = "1.0.0"
log = "0.4.20"
